global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # SNMP via snmp-exporter. Replace with your device IP(s).
  - job_name: "snmp"
    metrics_path: /snmp
    params:
      module: [if_mib]     # change if you mount a custom snmp.yml with other modules
    static_configs:
      - targets: ["192.0.2.10"]  # <-- replace
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
